config/routes.rb
Work2transcend::Application.routes.draw do
  devise_for :users
  resources :projects do
    post "like", to: "projects#upvote"
    post "dislike", to: "projects#downvote"
    get 'tagged', to: "projects#tagged", as: :tagged
    put 'join_project', to: "projects#join_project"
    put 'leave_project', to: "projects#leave_project"
    delete 'remove_resource', to: "projects#remove_resource"

    resources :comments, only: [:index, :create, :destroy]
  end

  root :to => 'projects#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project, inverse_of: :project
  belongs_to :user, inverse_of: :comments
  validates_presence_of :body
end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_votable
  acts_as_taggable
  has_attached_file :resource1, removable: true
  has_attached_file :resource2, removable: true
  has_attached_file :resource3, removable: true
  has_attached_file :resource4, removable: true
  has_attached_file :resource5, removable: true
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
  belongs_to :user
  has_many :projectmembers
  has_many :users,
    through: :projectmembers
  has_many :comments
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :completion_status
  validates_numericality_of :completion_status, greater_than_or_equal_to: 0, less_than_or_equal_to: 100

  def self.search(search)
    if search
      Project.includes(:tags).where('tags.name ILIKE ? OR projects.title ILIKE ?',"%#{search}%", "%#{search}%").references(:tags)
    else
      all
    end
  end

end

app/models/projectmember.rb
class Projectmember < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates_uniqueness_of :user, scope: :project
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  acts_as_tagger
  acts_as_taggable
  acts_as_taggable_on :projects
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }, removable: true

  has_many :projectmembers
  has_many :projects,
    through: :projectmembers
  has_many :comments, inverse_of: :user

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :age
  validates_presence_of :state

  validates :first_name, format: { with: /\A[a-z]+\z/i }
  validates :last_name, format: { with: /\A[a-z]+\z/i }
  validates_numericality_of :age, greater_than: 0
  validates :state, format: { with: /\A[a-z]{2}\z/i }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :age, :state, :avatar]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name, :age, :state, :avatar, :remove_avatar]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @project = Project.find(params[:project_id])
    @comments = @project.comments
  end

  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.build(comment_params)
    @comment.user_id = current_user.id
    @user = "#{@comment.user.first_name} #{@comment.user.last_name}"
    respond_to do |format|
      if @comment.save
        format.json { render json: {comment: @comment, user: @user} }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to :back, notice: 'Your comment was successfully destroyed' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, notice: 'There was an issue deleting your comment.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/projectmembers_controller.rb
class ProjectmembersController < ApplicationController
  def index
    @projectmembers = Projectmember.all
  end

  def new
    @user = current_user
    @project = Project.find(params[:id])
    @projectmember = Projectmember.new(user_id: @user.id, project_id: @project.id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :is_admin, only: [:destroy]
  respond_to :html, :json

  def remove_resource(resource)
    set_project
    @project.resource.destroy
    redirect_to project_path(@project)
  end

  def group_email
    set_project
  end

  def join_project
    @project = Project.find(params[:project_id])
    @project.users << current_user
    redirect_to project_path(@project), notice: 'Welcome aboard!'
  end

  def leave_project
    @project = Project.find(params[:project_id])
    @project.users.destroy(current_user)
    redirect_to project_path(@project), notice: 'You\'ve been successfully removed from the group. We\'re sorry to see you go!'
  end

  def index
    @projects = Project.all.includes(:tags).search(params[:search])
  end

  def new
    @project = Project.new
  end

  def show
    set_project
    @comments = @project.comments
    @comment = Comment.new
  end

  def edit
    set_project
  end

  def create
    @project = Project.new(project_params)
    @project.users << current_user
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        ProjectMailer.project_confirmation(@project, current_user).deliver
        format.html { redirect_to project_path(@project), notice: 'Project successfully added!' }
        format.json { render json: @project }
      else
        format.html {redirect_to :back, notice: 'There was a problem saving your project, please try again.' }
        format.json { head :no_content }
      end
    end
  end

  def update
    set_project
    @project.update_attributes!(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    set_project.destroy
    redirect_to projects_path, notice: 'Project removed... We are sad to see it go!'
  end

  def upvote
    @project = Project.find(params[:project_id])
    @project.liked_by current_user
    respond_to do |format|
      format.json {render json: [@project, (@project.likes.size - @project.dislikes.size)] }
    end
  end

  def downvote
    @project = Project.find(params[:project_id])
    @project.downvote_from current_user
    respond_to do |format|
      format.json {render json: [@project, (@project.likes.size - @project.dislikes.size)] }
    end
  end

  def tagged
    if params[:tag].present?
      @projects = Project.tagged_with(params[:tag])
    else
      @projects = Project.all
    end
  end

  private

  def is_admin
    current_user.role == "admin"
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :completion_status, :success_status, :tag_list, :avatar, :resource1, :resource2, :resource3, :resource4, :resource5, :remove_resource1, :remove_resource2, :remove_resource3, :remove_resource4, :remove_resource5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Ohu" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Cardo:400,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <% unless !user_signed_in? %>
      <div class="page">
        <div class="off-canvas-wrap">
          <div class="inner-wrap">
            <nav class="tab-bar">
              <a class="left-off-canvas-toggle menu-icon">
                <span>
                  <%= current_user.first_name %>
                </span>
              </a>
            </nav>

            <aside class="left-off-canvas-menu">
              <ul class="off-canvas-list">

                <% if user_signed_in? && current_user.avatar_file_size.nil? %>
                  <div class="avatar_wrapper">
                    <li><%= link_to image_tag('Bubba.jpg'), edit_user_registration_path %></li>
                  </div>
                <% elsif user_signed_in? && !(current_user.avatar_file_size.nil?) %>
                  <div class="avatar">
                    <li><%= link_to image_tag(current_user.avatar), edit_user_registration_path, :class => "avatar" %></li>
                  </div>
                <% end %>

                <div class="home">
                  <li><%= link_to "Home", root_path %></li>
                </div>

                <div class="new_project">
                  <li><%= link_to "Start a Project!", new_project_path %></li>
                </div>

                <div class="user_projects">
                  <% if !current_user.projects.nil? %>
                    <% current_user.projects.each do |project| %>
                      <li><%= link_to "#{project.title}", project_path(project) %></li>
                    <% end %>
                  <% else %>
                    <li><%= link_to "Start a Project!", new_project_path %></li>
                  <% end %>
                </div>

                <% if user_signed_in? %>
                  <div class="signout">
                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                  </div>
                <% else %>
                  <div class="signup_signin">
                    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                    <li><%= link_to 'Sign In', new_user_session_path %></li>
                  </div>
                <% end %>

              </ul>
            </aside>

            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <% end %>

          <div class="main-content">
            <%= yield %>
          </div>

          </div>
        </div>
      </div>

    <%= javascript_include_tag "application" %>
    <%= yield :extra_footer %>
  </body>
</html>

app/views/projects/_comments.html.erb
<% @project.comments.each do |comment| %>
  <div class="comment">
    <strong><%= comment.user.first_name %> <%= comment.user.last_name %></strong>
    <br><br>
    <%= comment.body %><br><br>
    <%= link_to 'Delete', project_comment_path(@project, comment), method: :delete %>
    <br><hr>
  </div>
<% end %>

app/views/projects/_form.html.erb
<% if user_signed_in? %>
  <%= simple_form_for @project do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :completion_status, label: "Completion Status" %>
    <%= f.input :success_status, label: "Success Status" %>
    <%= f.input :tag_list, label: "Tag List", action: :tag %>
    <%= f.input :avatar %>
    <%= f.input :resource1, label: "Resource 1" %>
    <%= f.input :resource2, label: "Resource 2" %>
    <%= f.input :resource3, label: "Resource 3" %>
    <%= f.input :resource4, label: "Resource 4" %>
    <%= f.input :resource5, label: "Resource 5" %>
    <%= f.submit %>
  <% end %>
<% else %>
  <h1>You're not allowed here!</h1>
<% end %>

app/views/projects/_projects.html.erb
<% @projects.sort.each do |project| %>

  <div class="project">

    <div class="pic-container" <% if !project.avatar_file_size.nil? %> style="background-image: url(<%= project.avatar %>);" <% end %>>
      <h3>
        <span class="join-button">
          <%= link_to "+", project_join_project_path(project), method: :put %>
        </span>
        <%= project.projectmembers.first.user.first_name + " " + project.projectmembers.first.user.last_name %>
      </h3>
      <h4>
        <%= project.projectmembers.first.user.state %>
      </h4>
      <h2 class="completion">
        <%= project.completion_status %>%
      </h2>
      <h3 class="title">
        <%= link_to "#{project.title}", project %>
      </h3>
    </div>

    <hr>

    <div class="index">
      <%= render partial: 'projects/voting', locals: {project: project} %>
    </div>

    <p>
      <% project.tags.any? %>
        <% project.tags.sort{|a,b| a.name <=> b.name}.first(3).each do |tag| %>
        / <%= tag.name %> /
        <% end %>
    </p>

    <% if user_signed_in? && project.user_id == current_user.id && current_user.role == "user" %>
      <div class="edit-links">
        <%= link_to 'Edit', edit_project_path(project) %><br>
        <%= link_to "Destroy #{project.title}", project, method: :delete, data: { confirm: 'Are you sure about that?'} %>
      </div>
    <% elsif user_signed_in? && current_user.role == "admin" %>
      <div class="edit-links">
        <%= link_to 'Edit', edit_project_path(project) %><br>
        <%= link_to "Destroy #{project.title}", project, method: :delete, data: { confirm: 'Are you sure about that?'} %>
      </div>
    <% elsif user_signed_in? && project.user_id != current_user.id && current_user.role == "user" %>
      <br>
    <% end %>

  </div>

<% end %>

app/views/projects/_voting.html.erb
<div id="project<%= project.id %>_votes_size" class="votes_size">
  <strong>Score: </strong><%= project.likes.size - project.dislikes.size %>
</div>

<div class="upvote">
  <%= link_to "<button>▲</button>".html_safe, project_like_path(project), method: :post, data: { 'vote-button' => 'create' }, remote: true %>
</div>

<div class="downvote">
  <%= link_to "<button>▼</button>".html_safe, project_dislike_path(project), method: :post, data: { 'vote-button' => 'create' }, remote: true %>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'projects/form', project: @project %>

<%= link_to 'Back to Project Page', projects_path %>

app/views/projects/index.html.erb
<% unless user_signed_in? %>

  <div class="welcome">
  </div>

  <div class="introduction">
    <p>One of the greatest problems in community-based projects is the sharing of information. This website seeks to bridge the gaps between organizations and those invested in the community. Sign up and start a project today! Welcome to Ohu!</p>
  </div>

  <h3>
    <div class="signin">
      <%= link_to 'Sign In', new_user_session_path %>
    </div>
  </h3>

  <div class="pre-banner">
    <p>Not a member?</p>
    <%= link_to "<button>Sign Up</button>".html_safe, new_user_registration_path %>
  </div>

  <h1 class="banner">
    Find a <strong>Project</strong> // Find a <strong>Passion</strong>
  </h1>

  <%= form_tag projects_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search for a project by tag or title!" %>
  <% end %>

  <hr>

  <%= render 'projects' %><br><br>

<% else %>

  <h1 class="banner">
    Find a <strong>Project</strong> // Find a <strong>Passion</strong>
  </h1>

  <%= form_tag projects_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search for a project by tag or title!" %>
  <% end %>

  <hr>

  <%= render 'projects' %><br>

<% end %>

app/views/projects/new.html.erb
<h1>Add your project!</h1>

<%= render 'projects/form', project: @project %>

app/views/projects/show.html.erb
<div class="single-project">

  <% if @project.users.include?(current_user) %>
    <span class="leave-button">
      <%= link_to "-", project_leave_project_path(@project), method: :put %>
    </span>
  <% else %>
    <span class="join-button">
      <%= link_to "+", project_join_project_path(@project), method: :put %>
    </span>
  <% end %>

  <% if @project.avatar_file_size.nil? %>
    <%= image_tag 'Bubba.jpg', :class => "project-image" %>
  <% else %>
    <%= image_tag @project.avatar, :class => "project-image" %>
  <% end %>

  <h1>
    <%= @project.title %> (<%= @project.completion_status %>%)
  </h1>

  <p>
    <strong>Description:</strong><br>
    <%= @project.description %>
  </p>

  <p>
    <strong>Success Information:</strong><br>
    <%= @project.success_status %>
  </p>

  <p>
    <strong>Members: </strong>
    <%= @project.users.count %>
  </p>

  <% @project.users.each do |member| %>
    <% if member.avatar_file_size.nil? %>
      <p class="avatar">
        <%= image_tag 'Bubba.jpg', :class => "member-avatar" %><br>
        <%= member.first_name %> <%= member.last_name %>
      </p>
    <% else %>
      <p class="avatar">
        <%= image_tag member.avatar, :class => "member-avatar" %><br>
        <%= member.first_name %> <%= member.last_name %>
      </p>
    <% end %>
  <% end %>

  <hr>

  <p class="resources">
    <strong>Resources: </strong><br>
    <% if @project.user_id == current_user.id || current_user.role == "admin" %>

      <%= simple_form_for(@project) do |f| %>

        <% unless @project.resource1_file_name.nil? %>
          <div class="resource">
            <%= image_tag @project.resource1, :class => "resource_pic" %>
              <%= f.input :resource1, label: "Replace '#{@project.resource1_file_name}'" %>
              <%= f.input :remove_resource1, as: :boolean, label: "Delete Resource 1?" %>
          </div>
        <% end %>
        <% unless @project.resource2_file_name.nil? %>
          <div class="resource">
            <%= image_tag @project.resource2, :class => "resource_pic" %>
              <%= f.input :resource2, label: "Replace '#{@project.resource2_file_name}'" %>
              <%= f.input :remove_resource2, as: :boolean, label: "Delete Resource 2?" %>
          </div>
        <% end %>
        <% unless @project.resource3_file_name.nil? %>
          <div class="resource">
            <%= image_tag @project.resource3, :class => "resource_pic" %>
              <%= f.input :resource3, label: "Replace '#{@project.resource3_file_name}'" %>
              <%= f.input :remove_resource3, as: :boolean, label: "Delete Resource 3?" %>
          </div>
        <% end %>
        <% unless @project.resource4_file_name.nil? %>
          <div class="resource">
            <%= image_tag @project.resource4, :class => "resource_pic" %>
              <%= f.input :resource4, label: "Replace '#{@project.resource4_file_name}'" %>
              <%= f.input :remove_resource4, as: :boolean, label: "Delete Resource 4?" %>
          </div>
        <% end %>
        <% unless @project.resource5_file_name.nil? %>
          <div class="resource">
            <%= image_tag @project.resource5, :class => "resource_pic" %>
              <%= f.input :resource5, label: "Replace '#{@project.resource5_file_name}'" %>
              <%= f.input :remove_resource5, as: :boolean, label: "Delete Resource 5?" %>
          </div>
        <% end %>
        <% unless @project.resource1_file_name.nil? && @project.resource2_file_name.nil? && @project.resource3_file_name.nil? && @project.resource4_file_name.nil? && @project.resource5_file_name.nil? %>
          <br>
          <%= f.submit %>
        <% end %>

      <% end %>

    <% elsif @project.user_id != current_user.id %>
      <% unless @project.resource1_file_name.nil? %>
        <div class="resource">
          <%= image_tag @project.resource1, :class => "resource_pic" %>
        </div>
      <% end %>

      <% unless @project.resource2_file_name.nil? %>
        <div class="resource">
          <%= image_tag @project.resource2, :class => "resource_pic" %>
        </div>
      <% end %>

      <% unless @project.resource3_file_name.nil? %>
        <div class="resource">
          <%= image_tag @project.resource3, :class => "resource_pic" %>
        </div>
      <% end %>

      <% unless @project.resource4_file_name.nil? %>
        <div class="resource">
          <%= image_tag @project.resource4, :class => "resource_pic" %>
        </div>
      <% end %>

      <% unless @project.resource5_file_name.nil? %>
        <div class="resource">
          <%= image_tag @project.resource5, :class => "resource_pic" %>
        </div>
      <% end %>

    <% end %>
  </p>

  <br>

  <p>
    <strong>Tags: </strong><% @project.tags.any? %>
    <% @project.tags.sort.each do |tag| %>
      <%= tag.name %>
    <% end %>
  </p>

  <div class="show">
    <%= render partial: 'projects/voting', locals: {project: @project} %>
  </div>

  <hr>

  <div id="comments_count">
    <p>
      Total Comments: <%= @project.comments.count %>
    </p>
  </div>

  <hr>

  <div id="comments">
    <%= render 'comments' %>
  </div>

  <% if @project.users.include?(current_user) || current_user.role == "admin" %>
    <h3>Add Your Comment:</h3>
    <%= simple_form_for [@project, @comment] do |f| %>
      <%= f.input :body %>
      <%= f.submit %>
    <% end %>
  <% end %><br>

  <% if @project.user_id == current_user.id || current_user.role = "admin" %>
    <%= link_to 'Edit Project', edit_project_path %>
  <% end %>
</div>